diary/urls.py
from django.urls import path
from . import views
app_name = 'sinx'

urlpatterns = [

	
	path("", views.all_courses, name = "sinx"),
	path("overview/<int:course_id>/", views.course_overview, name = "course-overview"),
	path("rate/<int:course_id>/", views.course_rating, name = "course-rating"),
	path("search-courses/", views.search_courses, name = "search-courses"),
	path("search-courses/<str:tag>/", views.search_courses_by_tag, name = "search-courses-by-tag"),
	path("add-to-watchlist/<int:course_id>/", views.add_to_watchlist, name = "add-to-watchlist"),
	path("view-watchlist/", views.view_watchlist, name = "view-watchlist"),
	path("share-course/<int:course_id>/", views.share, name = "share"),
	path("delete-shared-course/<int:course_id>/<int:club_id>/", views.delete_shared_course, name = "delete-shared-course"),
	path("delete-from-watchlist/<int:course_id>/", views.manage_watchlist, name = "delete-from-watchlist"),



]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path
#from django.conf.urls import url
from accounts.views import index, donation
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("", index, name="index"),
    path('admin/', admin.site.urls),
    #path('chat/', include('django_chatter.urls', namespace = 'django_chatter'), name="chat"),
    path('accounts/', include('accounts.urls')),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
    path('users/', include('users.urls')),
    #path('courses/', include('courses.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('qna/', include('doubts.urls', namespace='qna')),
    path('quiz/', include('quizes.urls', namespace='quizes')),
    path('courses/', include('diary.urls', namespace = 'sinx')),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('accounts/password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('accounts/password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
    path("suPpoRt/", donation, name = "support"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [

    path("register/", views.register, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("delete-account/", views.deleteaccount, name="delete-account"),
    path("update-info/<int:pk>/", views.UpdateInfo.as_view(), name="update-info"),
    path("verify/<str:auth_token>/", views.verify, name="verify"),

]

sinx/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime
#from PIL import Image
from django_resized import ResizedImageField
from taggit.managers import TaggableManager


class Course(models.Model):

	name = models.CharField(max_length = 1000)
	author = models.CharField(max_length = 1000)
	tags = TaggableManager(related_name="course_tags")
	description = models.CharField(max_length = 5000)
	image = ResizedImageField(size=[300, 300], upload_to = "images/", null = True, blank = True)
	about = models.TextField(null = True, blank = True)
	link = models.URLField(max_length = 2000)
	overall_rating = models.IntegerField(default = 0)


	def __str__(self):

		return f"{self.name}"

	class  Meta:

		verbose_name_plural = "Courses-sinx"
		ordering = ["-overall_rating"]

class CourseDetail(models.Model):


	CHOICES = (

		('Videos', 'Videos'),
		('Textual', 'Textual'),
		('Hybrid', 'Hybrid'),
	)

	course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="course_details")
	price = models.IntegerField(default = 0)
	catagory = models.CharField(max_length = 250, default="Computer Science")
	platform = models.CharField(max_length = 1000, default="YouTube")
	released_date = models.DateField(null = True, blank = True)
	country = models.CharField(max_length = 1000, default="India")
	language = models.CharField(max_length = 250, default="English")
	price = models.IntegerField(default = 0)
	duration = models.IntegerField(default=4)
	certificate = models.BooleanField(default = False)
	material_type = models.CharField(max_length = 25, choices = CHOICES, default="Videos")
	added_by = models.CharField(max_length = 1000, default="Neesham")


	def __str__(self):

		return f"{self.course.name}--Details"

	class  Meta:
		verbose_name_plural = "Courses-details"
		

class Rating(models.Model):

	course = models.ForeignKey(Course, on_delete = models.CASCADE)
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	review = models.CharField(max_length = 3000, null = True, blank = True)
	rating = models.IntegerField(default = 0)

	def __str__(self):

		return f"{self.user.username} rate {self.course.name} {self.rating}"

	class  Meta:

		verbose_name_plural = "Course-Ratings"


class TotalRating(models.Model):
	course = models.ForeignKey(Course, on_delete = models.CASCADE)
	total_rating = models.IntegerField(default = 0)

	def __str__(self):

		return f"{self.course.name} has {self.total_rating} rating."

sinx/views.py
from django.shortcuts import render
from sinx.models import Course, Rating, TotalRating, CourseDetail
from django.http import HttpResponseRedirect, request, HttpResponse, JsonResponse
from django.contrib import messages
from django.core.paginator import Paginator
# Create your views here.

def all_courses(request):

	courses = Course.objects.all()
	p = Paginator(courses, 10)
	page = request.GET.get('page', 1)
	courses = p.page(page)
	return render(request, "sinx/courses.html", {"courses": courses})


def course_overview(request, course_id):

	course = Course.objects.get(id = course_id)
	reviews = Rating.objects.filter(course = course)
	details = CourseDetail.objects.get(course = course)
	return render(request, "sinx/course-rating.html", {"course": course, "reviews": reviews, "details": details})


def course_rating(request, course_id):

	if request.method == 'POST':

		rating, review = request.POST['rating'], request.POST['review']
		course = Course.objects.get(id = course_id)
		foo, created = Rating.objects.get_or_create(course = course, user = request.user)
		total, created = TotalRating.objects.get_or_create(course = course)

		bar = Rating.objects.filter(course = course)
	
		if created:
			print(rating)
			foo.rating = int(rating)
			foo.review = review
			foo.save()
			total.total_rating += int(rating)
			total.save()

			per = (total.total_rating) / (len(bar))
			course.overall_rating = per
			course.save()

			messages.success(request, "Thanks for rating this course!")
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

		messages.success(request, "You can only rate once.")
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))




def search_courses(request):

	if request.method == 'POST':

		tag = request.POST['course-tag'].lower()

		query = Course.objects.filter(tags__name__in = [tag])
		flag1 = False


		if len(query) == 0:
			flag1 = True



		return render(request, "sinx/courses.html", {"courses": query, "flag": True, "flag1": flag1})


def search_courses_by_tag(request, tag):


	query = Course.objects.filter(tags__name__in = [tag])
	flag1 = False


	if len(query) == 0:
		flag1 = True

	return render(request, "sinx/courses.html", {"courses": query, "flag": True, "flag1": flag1})

sinx/templates/sinx/course-rating.html
{% extends "accounts/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}
{% block title %}
{{course.name}}
{% endblock %}

{% block script %}



  <meta property="og:title" content="Hey, look at {{course.name}} course. It's quite popular on diarygreenson page." />
  <meta property="og:url" content="https://www.diarygreenson.herokuapp.com/overview/{{course.id}}/" />
  <meta property="og:type"               content="article" />
  <meta property="og:image" content="{{course.image.url}}" />
  <meta property="og:description" content="Hey, look at {{course.name}} coure. It's quite popular on diarygreenson page." />
  <meta property="og:site_name" content="Diarygreenson" />



  <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>

  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=61cfed3106175100190c1344&product=sop' async='async'></script>

  <link rel="stylesheet" href="{% static 'sinx/styles.css' %}">
  <link rel="stylesheet" href="{% static 'sinx/stories.css' %}">

  <style type="text/css">
    .choice {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      text-align: center;
      padding: 20px;
      display: block;
    }
    span.scale-rating{
    margin: 5px 0 15px;
        display: inline-block;
       
        width: 100%;
       
    }
    span.scale-rating>label {
      position:relative;
        -webkit-appearance: none;
      outline:0 !important;
        border: 1px solid grey;
        height:33px;
        margin: 0 5px 0 0;
      width: calc(10% - 7px);
        float: left;
      cursor:pointer;
    }

    span.scale-rating label {
      position:relative;
        -webkit-appearance: none;
      outline:0 !important;
        height:33px;
          
        margin: 0 5px 0 0;
      width: calc(10% - 7px);
        float: left;
      cursor:pointer;
    }

    span.scale-rating input[type=radio] {
      position:absolute;
        -webkit-appearance: none;
      opacity:0;
      outline:0 !important;
        /*border-right: 1px solid grey;*/
        height:33px;
     
        margin: 0 5px 0 0;
      
      width: 100%;
        float: left;
      cursor:pointer;
      z-index:3;
    }
    span.scale-rating label:hover{
    background:#fddf8d;
    }
    span.scale-rating input[type=radio]:last-child{
    border-right:0;
    }
    span.scale-rating label input[type=radio]:checked ~ label{
        -webkit-appearance: none;
     
        margin: 0;
      background:#fddf8d;
    }
    span.scale-rating label:before
    {
      content:attr(value);
        top: 7px;
        width: 100%;
        position: absolute;
        left: 0;
        right: 0;
        text-align: center;
        vertical-align: middle;
      z-index:2;
    }




  </style>

    
{% endblock %}

{% block main %}
  
{% for msg in messages %}
   
    <p class="text-success text-center" id = "msg-container">{{msg}}</p>

                
{% endfor %}


      <section class="cta-section theme-bg-light py-5 text-start">
        <div class="container text-center single-col-max-width">

          <div id="particles-js">

            <div class="containers">

              <div class="typed-out mb-5 mt-5 text-info" style="font-size: 24px; font-family: monospace;">Find best course for...</div>


              
            </div>
            


            <div class="single-form-max-width pt-3 mx-auto">
                <form class="signup-form row g-2 g-lg-2 align-items-center" method="post" action="{% url 'sinx:search-courses' %}">
                  {% csrf_token %}
                          <div class="col-12 col-md-10">
                              <label class="sr-only" for="semail">Search courses</label>
                              <input type="search" id="semail" name="course-tag" class="form-control me-md-1 semail" placeholder="Enter topic name">
                          </div>
                          <div class="col-12 col-md-2">
                              <button type="submit" class="btn btn-primary">Search</button>
                          </div>
                </form>

            </div>
            
          </div> 



        </div>
      </section>


    
    <section class="blog-list px-3 py-5 p-md-5">
      <div class="container single-col-max-width">

        <div class="item mb-5">
          <div class="row g-3 g-xl-0">
            <div class="col-2 col-xl-3">
                <img class="img-fluid post-thumb " src="{{course.image.url}}" alt="image">
            </div>
            <div class="col">
              <h3 class="title mb-1"><a class="text-link" href="">{{course.name}}</a></h3>
              Tags: |
              {% for j in course.tags.all %}
                <span class="comment"><a href="/sinx/search-courses/{{j}}/">{{j}}</a> |</span>

              {% endfor %}
              
              <hr>
              <h3 class="title mb-3 text-muted">Course Info</h3>
              <p><b>Author</b>: {{course.author}}</p>
              <p><b>Rating</b>: <mark>{{course.overall_rating}}</mark></p>
              <p><b>Platform</b>: {{details.platform}}</p>
              <p><b>Language</b>: {{details.language}}</p>
              {% if details.price == 0 %}<p><b>Fees</b>: <mark>Free</mark></p>{% else %}<p><b>Fees</b>: {{details.price}}</p>{% endif %}

              <p><b>Certificate</b>: {% if details.certificate %} Yes {% else %} No {% endif %}</p>
              <p><b>Material Type</b>: {{details.material_type}}</p>
              <p><b>Duration</b>: {{details.duration}} hours</p>
              
              <h3 class="title mt-5 text-muted">About</h3>
              <div class="intro mt-3" style="font-size: 22px;">{{course.about}}</div>
              <h3 class="title mt-3"><a class="text-link" href="{{course.link}}">Visit this course</a></h3>
              <br>

            </div><!--//col-->
          </div><!--//row-->
        </div><!--//item-->




    {% if request.user.is_authenticated %} 
      <nav class="blog-nav nav nav-justified my-5">
        <a class="nav-link-next nav-item nav-link rounded" href="#" data-toggle="collapse" data-target="#story-box" aria-expanded="false" aria-controls="story-box">Rate this course</a>



      </nav>



      <div class="collapse" id="story-box">

        <form class="p-4 p-md-5 border rounded-3" action="{% url 'sinx:course-rating' course.id %}" method="post">

          {% csrf_token %}

            <span class="text-start">Rate</span>
            <span class="scale-rating" id="rating">
              <label value="1">
              <input type="radio" name="rating" >
              <label style="width:100%;"></label>
              </label>
              <label value="2">
              <input type="radio" name="rating" >
              <label style="width:100%;"></label>
              </label>
              <label value="3">
              <input type="radio" name="rating">
              <label style="width:100%;"></label>
              </label>
              <label value="4">
              <input type="radio" name="rating">
              <label style="width:100%;"></label>
              </label>
              <label value="5">
              <input type="radio" name="rating">
              <label style="width:100%;"></label>
              </label>
              <label value="6">
              <input type="radio" name="rating">
              <label style="width:100%;"></label>
              </label>
              <label value="7">
              <input type="radio" name="rating">
              <label style="width:100%;"></label>
              </label>
              <label value="8">
              <input type="radio" name="rating">
              <label style="width:100%;"></label>
              </label>
              <label value="9">
              <input type="radio" name="rating">
              <label style="width:100%;"></label>
              </label>
              <label value="10">
              <input type="radio" name="rating" value="10">
              <label style="width:100%;"></label>
              </label>
            </span>


          <div class="form-floating">
            <textarea class="form-control" placeholder="Leave your review here" id="floatingTextarea" name="review"></textarea>
            <label for="floatingTextarea">Review</label>
          </div>


          <div class="text-center">
            <button type="submit" class="btn btn-primary mb-5 mt-3">Rate</button>
          </div>

        </form>



              
      </div>

      {% else %}

        <div class="text-center">
          <a href="{% url 'users:register' %}" class="filled-button mt-2" style="text-decoration: none;">Sign up</a>
          
        </div>

      {% endif %}
      
      </div>
    </section>

    <hr>


    <section class="gradient-custom">
      <div class="container my-5 py-5">
        <div class="row d-flex justify-content-center">
          <div class="col-md-12 col-lg-10 col-xl-8">
            <div class="card">
              <div class="card-body p-4">
                <h4 class="text-center mb-4 pb-2">{{reviews|length}} Reviews</h4>

                <div class="row">
                  <div class="col">

                    {% if reviews %}
                    {% for i in reviews %}
                    <div class="d-flex flex-start mt-5">
                      <img
                        class="rounded-circle shadow-1-strong me-3"
                        src="https://ui-avatars.com/api/?name={{i.user.username}}"
                        alt="avatar"
                        width="65"
                        height="65"
                      />
                      <div class="flex-grow-1 flex-shrink-1">
                        <div>
                          <div class="d-flex justify-content-between align-items-center">
                            <p class="mb-1">
                              <b>{{i.user.username}}</b> <span class="small"><!-- 2 hours ago--></span>
                            </p>
                            <!--<a href="#!"
                              ><i class="fas fa-reply fa-xs"></i
                              ><span class="small"> reply</span></a
                            >-->
                          </div>
                          <p class="small mb-0">
                            {{i.review}}
                          </p>
                        </div>


                      </div>
                    </div>
                    {% endfor %}
                    {% endif %}

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>





{% endblock %}

{% block ajaxbox %}


    <script>

        const ele = document.getElementById("msg-container")
        setTimeout(function(){

            ele.style.display = "none";
            },
         3000);
    </script>
{% endblock %}

sinx/templates/sinx/courses.html
{% extends "accounts/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}
{% block title %}
Diary
{% endblock %}

{% block script %}

  <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  
  <link rel="stylesheet" href="{% static 'sinx/styles.css' %}">
  <link rel="stylesheet" href="{% static 'sinx/stories.css' %}">


    
{% endblock %}

{% block main %}
  
{% for msg in messages %}
   
    <p class="text-success text-center" id = "msg-container">{{msg}}</p>

                
{% endfor %}


      <section class="cta-section theme-bg-light py-5 text-start">
        <div class="container text-center single-col-max-width">


          

              <div class="containers">

                <div class="typed-out mb-5 mt-5 text-info" style="font-size: 24px; font-family: monospace;">Find best course for...</div>


                
              </div>


              <div class="mb-3">
                
                <span class="badge bg-info text-dark"><a href="/courses/search-courses/python/" class="text-dark text-decoration-none">Python</a></span>
                <span class="badge bg-info text-dark"><a href="/courses/search-courses/competitive programming/" class="text-dark text-decoration-none">Competitive programming</a></span>
                <span class="badge bg-info text-dark"><a href="/courses/search-courses/android/" class="text-dark text-decoration-none">Android</a></span>
                <span class="badge bg-info text-dark"><a href="/courses/search-courses/web development/" class="text-dark text-decoration-none">Web development</a></span>
                <span class="badge bg-info text-dark"><a href="/courses/search-courses/investing/" class="text-dark text-decoration-none">Investing</a></span>
                <span class="badge bg-info text-dark"><a href="/courses/search-courses/machine learning/" class="text-dark text-decoration-none">Machine learning</a></span>

              </div>


              
              <!--<div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>-->



            <div class="single-form-max-width pt-3 mx-auto">
                <form class="signup-form row g-2 g-lg-2 align-items-center" method="post" action="{% url 'sinx:search-courses' %}">
                  {% csrf_token %}
                          <div class="col-12 col-md-10">
                              <label class="sr-only" for="semail">Search courses</label>
                              <input type="search" id="semail" name="course-tag" class="form-control me-md-1 semail" placeholder="Enter topic name">
                          </div>
                          <div class="col-12 col-md-2">
                              <button type="submit" class="btn btn-primary">Search</button>
                          </div>
                </form>

            </div>
            

      </section>

    <section class="blog-list px-3 py-5 p-md-5">
      <div class="container single-col-max-width">


        {% for i in courses %}
        <div class="item mb-5">
          <div class="row g-3 g-xl-0">
            <div class="col-2 col-xl-3">
                <img class="img-fluid post-thumb " src="{{i.image.url}}" alt="image">
            </div>
            <div class="col">
              <h3 class="title mb-1"><a class="text-link" href="{% url 'sinx:course-overview' i.id %}">{{i.name}}</a></h3>
              <div class="meta mb-1"><span class="date">Author: {{i.author}}</span><span class="comment"><mark>Rating {{i.overall_rating}}</mark></span>
                <!--<span class="comment">Platform: {{i.course_details.platform}}</span>{% if i.course_details.price == 0 %}<span class="comment">Fees: <mark>Free</mark></span>{% else %}<span class="comment">Fees: {{i.course_details.price}}</span>{% endif %}</div>-->


              <div class="intro mt-5">{{i.description|safe|truncatewords:30}}</div>

              <a class="text-link text-info" href="{% url 'sinx:course-overview' i.id %}">Know more &rarr;</a>
            </div><!--//col-->
          </div><!--//row-->
        </div><!--//item-->

        {% empty %}

          {% if flag %}
          <h4 class="text-center">No course found.</h4>
          {% else %}
          <h4 class="text-center">No courses added yet.</h4>
          {% endif %}


        {% endfor %}

          {% if flag1 %}
          {% else %}
            <h4 class="text-center">No more courses.</h4>

          {% endif %}
              
      </div>
      
      </div>
    </section>




{% endblock %}

{% block ajaxbox %}

    <script>

        const ele = document.getElementById("msg-container")
        setTimeout(function(){

            ele.style.display = "none";
            },
         3000);


    </script>
{% endblock %}