diary/urls.py
from django.urls import path
from . import views
app_name = 'sinx'

urlpatterns = [

	
	path("", views.all_courses, name = "sinx"),
	path("overview/<int:course_id>/", views.course_overview, name = "course-overview"),
	path("rate/<int:course_id>/", views.course_rating, name = "course-rating"),
	path("search-courses/", views.search_courses, name = "search-courses"),
	path("search-courses/<str:tag>/", views.search_courses_by_tag, name = "search-courses-by-tag"),
	path("add-to-watchlist/<int:course_id>/", views.add_to_watchlist, name = "add-to-watchlist"),
	path("view-watchlist/", views.view_watchlist, name = "view-watchlist"),
	path("share-course/<int:course_id>/", views.share, name = "share"),
	path("delete-shared-course/<int:course_id>/<int:club_id>/", views.delete_shared_course, name = "delete-shared-course"),
	path("delete-from-watchlist/<int:course_id>/", views.manage_watchlist, name = "delete-from-watchlist"),



]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path
#from django.conf.urls import url
from accounts.views import index, donation
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("", index, name="index"),
    path('admin/', admin.site.urls),
    #path('chat/', include('django_chatter.urls', namespace = 'django_chatter'), name="chat"),
    path('accounts/', include('accounts.urls')),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
    path('users/', include('users.urls')),
    #path('courses/', include('courses.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('qna/', include('doubts.urls', namespace='qna')),
    path('quiz/', include('quizes.urls', namespace='quizes')),
    path('courses/', include('diary.urls', namespace = 'sinx')),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('accounts/password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('accounts/password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
    path("suPpoRt/", donation, name = "support"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

diary/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import datetime
#from PIL import Image
from accounts.models import clubInfo
from django_resized import ResizedImageField
from taggit.managers import TaggableManager


class Course(models.Model):

	CHOICES = (

		('Videos', 'Videos'),
		('Textual', 'Textual'),
		('Hybrid', 'Hybrid'),
	)

	name = models.CharField(max_length = 1000)
	author = models.CharField(max_length = 1000)
	tags = TaggableManager(related_name="course_tags")
	description = models.CharField(max_length = 5000)
	image = ResizedImageField(size=[300, 300], upload_to = "images/", null = True, blank = True)
	about = models.TextField(null = True, blank = True)
	link = models.URLField(max_length = 2000)
	overall_rating = models.IntegerField(default = 0)
	price = models.IntegerField(default = 0)
	catagory = models.CharField(max_length = 250, default="Computer Science")
	platform = models.CharField(max_length = 1000, default="YouTube")
	released_date = models.DateField(null = True, blank = True)
	country = models.CharField(max_length = 1000, default="India")
	language = models.CharField(max_length = 250, default="English")
	price = models.IntegerField(default = 0)
	duration = models.IntegerField(default=4)
	certificate = models.BooleanField(default = False)
	material_type = models.CharField(max_length = 25, choices = CHOICES, default="Videos")
	added_by = models.CharField(max_length = 1000, default="Neesham")


	def __str__(self):

		return f"{self.name}"

	class  Meta:

		verbose_name_plural = "Courses-sinx"
		ordering = ["-overall_rating"]



class Rating(models.Model):

	course = models.ForeignKey(Course, on_delete = models.CASCADE)
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	review = models.CharField(max_length = 3000, null = True, blank = True)
	rating = models.IntegerField(default = 0)

	def __str__(self):

		return f"{self.user.username} rate {self.course.name} {self.rating}"

	class  Meta:

		verbose_name_plural = "Course-Ratings"


class TotalRating(models.Model):
	course = models.ForeignKey(Course, on_delete = models.CASCADE)
	total_rating = models.IntegerField(default = 0)

	def __str__(self):

		return f"{self.course.name} has {self.total_rating} rating."



class Watchlist(models.Model):

	user = models.ForeignKey(User, on_delete = models.CASCADE)
	courses = models.ForeignKey(Course, on_delete = models.CASCADE)

	def __str__(self):

		return f"{self.user.username}'s playlist!"


class ShareCourse(models.Model):

	user = models.ForeignKey(User, on_delete=models.CASCADE)
	club = models.ForeignKey(clubInfo, on_delete = models.CASCADE)
	msg = models.TextField(default = "Hey, Look at this course it's quite popular on cosb diary.")
	timestamp = models.DateTimeField(auto_now_add = True)
	course = models.ForeignKey(Course, on_delete = models.CASCADE)
	views = models.IntegerField(default=0)

	def __str__(self):

		return f"{self.user.username} shared {self.course.name} in {self.club.name}!"

diary/forms.py
from django import forms


class ShareForm(forms.Form):

    message = forms.CharField(max_length = 3000, label = "Message(Optional)", required = False, widget = forms.Textarea(
    attrs ={
        'class':'form-control',
        'placeholder':'Hey, Look at this course!',
        'rows':5,
    }))

course_diary/views.py
from django.shortcuts import render, redirect
from course_diary.models import Course, Rating, TotalRating, Watchlist, ShareCourse
from django.http import HttpResponseRedirect, request, HttpResponse, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from accounts.models import Members, clubInfo
from .forms import ShareForm
# Create your views here.

def all_courses(request):

	courses = Course.objects.all()
	return render(request, "course_diary/courses.html", {"courses": courses})


def course_overview(request, course_id):

	course = Course.objects.get(id = course_id)
	
	added = False

	clubs = ""

	if request.user.is_authenticated:

		watchlist = Watchlist.objects.filter(user = request.user, courses=course)

		member, created = Members.objects.get_or_create(memname = request.user)

		clubs = member.club.all()

		if watchlist:
			added = True

	form = ShareForm()

	reviews = Rating.objects.filter(course = course)
	return render(request, "course_diary/course-rating.html", {"course": course, "reviews": reviews, "added": added, 'clubs': clubs, "form": form})


def course_rating(request, course_id):

	if request.method == 'POST':

		rating, review = request.POST['rating'], request.POST['review']

		course = Course.objects.get(id = course_id)
		foo, created = Rating.objects.get_or_create(course = course, user = request.user)
		total, created = TotalRating.objects.get_or_create(course = course)

		bar = Rating.objects.filter(course = course)
	
		if created:
			print(rating)
			foo.rating = int(rating)
			foo.review = review
			foo.save()

			total.total_rating += int(rating)
			total.save()

			per = (total.total_rating) / (len(bar))
			course.overall_rating = per
			course.save()

			messages.success(request, "Thanks for rating this course!")
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

		messages.success(request, "You can only rate once.")
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))




def search_courses(request):

	if request.method == 'POST':

		tag = request.POST['course-tag'].lower()

		query = Course.objects.filter(tags__name__in = [tag])
		flag1 = False


		if len(query) == 0:
			flag1 = True



		return render(request, "course_diary/courses.html", {"courses": query, "flag": True, "flag1": flag1})


def search_courses_by_tag(request, tag):


	query = Course.objects.filter(tags__name__in = [tag])
	flag1 = False


	if len(query) == 0:
		flag1 = True

	return render(request, "course_diary/courses.html", {"courses": query, "flag": True, "flag1": flag1})

@login_required
def add_to_watchlist(request, course_id):

	course = Course.objects.get(id = course_id)
	watchlist, created = Watchlist.objects.get_or_create(user = request.user, courses = course)

	return JsonResponse({"status": 1})

@login_required
def view_watchlist(request):

	courses = Watchlist.objects.filter(user = request.user)
	return render(request, "course_diary/courses.html", {"watchlist_courses": courses, "watchlist": True})


def share(request, course_id):

	if request.method == 'POST':

		form = ShareForm(request.POST)

		if form.is_valid():

			course = Course.objects.get(id = course_id)
			club_id = request.POST['club-name']
			club = clubInfo.objects.get(id = club_id)
			msg = request.POST['message']
			data = ShareCourse.objects.create(user = request.user, msg = msg, course = course, club = club)
			data.save()

			return redirect(f"/accounts/your-club/{club_id}/")

@login_required
def delete_shared_course(request, course_id, club_id):

	shared_course = ShareCourse.objects.get(id = course_id)

	if request.user == shared_course.user:

		shared_course.delete()

		messages.success(request, "Deleted Successfully.")
		return redirect(f"/accounts/your-club/{club_id}/")

	else:

		messages.success(request, "You don't have permissions to delete it.")
		return redirect(f"/accounts/your-club/{club_id}/")

@login_required
def manage_watchlist(request, course_id):

	course = Watchlist.objects.filter(courses = course_id, user = request.user)

	for i in course:

		i.delete()

	return redirect("sinx:view-watchlist")

diary/views.py
from django.shortcuts import render, redirect
from diary.models import Course, Rating, TotalRating, Watchlist, ShareCourse
from django.http import HttpResponseRedirect, request, HttpResponse, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from accounts.models import Members, clubInfo
from .forms import ShareForm
# Create your views here.

def all_courses(request):

	courses = Course.objects.all()
	return render(request, "course_diary/courses.html", {"courses": courses})


def course_overview(request, course_id):

	course = Course.objects.get(id = course_id)
	
	added = False

	clubs = ""

	if request.user.is_authenticated:

		watchlist = Watchlist.objects.filter(user = request.user, courses=course)

		member, created = Members.objects.get_or_create(memname = request.user)

		clubs = member.club.all()

		if watchlist:
			added = True

	form = ShareForm()

	reviews = Rating.objects.filter(course = course)
	return render(request, "course_diary/course-rating.html", {"course": course, "reviews": reviews, "added": added, 'clubs': clubs, "form": form})


def course_rating(request, course_id):

	if request.method == 'POST':

		rating, review = request.POST['rating'], request.POST['review']

		course = Course.objects.get(id = course_id)
		foo, created = Rating.objects.get_or_create(course = course, user = request.user)
		total, created = TotalRating.objects.get_or_create(course = course)

		bar = Rating.objects.filter(course = course)
	
		if created:
			print(rating)
			foo.rating = int(rating)
			foo.review = review
			foo.save()

			total.total_rating += int(rating)
			total.save()

			per = (total.total_rating) / (len(bar))
			course.overall_rating = per
			course.save()

			messages.success(request, "Thanks for rating this course!")
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

		messages.success(request, "You can only rate once.")
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))




def search_courses(request):

	if request.method == 'POST':

		tag = request.POST['course-tag'].lower()

		query = Course.objects.filter(tags__name__in = [tag])
		flag1 = False


		if len(query) == 0:
			flag1 = True



		return render(request, "course_diary/courses.html", {"courses": query, "flag": True, "flag1": flag1})


def search_courses_by_tag(request, tag):


	query = Course.objects.filter(tags__name__in = [tag])
	flag1 = False


	if len(query) == 0:
		flag1 = True

	return render(request, "course_diary/courses.html", {"courses": query, "flag": True, "flag1": flag1})

@login_required
def add_to_watchlist(request, course_id):

	course = Course.objects.get(id = course_id)
	watchlist, created = Watchlist.objects.get_or_create(user = request.user, courses = course)

	return JsonResponse({"status": 1})

@login_required
def view_watchlist(request):

	courses = Watchlist.objects.filter(user = request.user)
	return render(request, "course_diary/courses.html", {"watchlist_courses": courses, "watchlist": True})


def share(request, course_id):

	if request.method == 'POST':

		form = ShareForm(request.POST)

		if form.is_valid():

			course = Course.objects.get(id = course_id)
			club_id = request.POST['club-name']
			club = clubInfo.objects.get(id = club_id)
			msg = request.POST['message']
			data = ShareCourse.objects.create(user = request.user, msg = msg, course = course, club = club)
			data.save()

			return redirect(f"/accounts/your-club/{club_id}/")

@login_required
def delete_shared_course(request, course_id, club_id):

	shared_course = ShareCourse.objects.get(id = course_id)

	if request.user == shared_course.user:

		shared_course.delete()

		messages.success(request, "Deleted Successfully.")
		return redirect(f"/accounts/your-club/{club_id}/")

	else:

		messages.success(request, "You don't have permissions to delete it.")
		return redirect(f"/accounts/your-club/{club_id}/")

@login_required
def manage_watchlist(request, course_id):

	course = Watchlist.objects.filter(courses = course_id, user = request.user)

	for i in course:

		i.delete()

	return redirect("sinx:view-watchlist")

diary/templates/course_diary/courses.html
{% extends "accounts/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load humanize %}
{% block title %}
Diary
{% endblock %}

{% block script %}

  <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  
  <link rel="stylesheet" href="{% static 'course_diary/styles.css' %}">
  <link rel="stylesheet" href="{% static 'course_diary/stories.css' %}">


    
{% endblock %}

{% block main %}
  
{% for msg in messages %}
   
    <p class="text-success text-center" id = "msg-container">{{msg}}</p>

                
{% endfor %}


      <section class="cta-section theme-bg-light py-5 text-start">
        <div class="container text-center single-col-max-width">

            {% if watchlist %}
              <div class="container">
                <h4 class="text-center">Your Watchlist</h4>
              </div>
            {% endif %}
              <div class="containers">

                <div class="typed-out mb-5 mt-5 text-info" style="font-size: 24px; font-family: monospace;">Find best course for...</div>


                
              </div>


              <div class="mb-3">
                
                <span class="badge bg-info text-dark"><a href="/courses/search-courses/python/" class="text-dark text-decoration-none">Python</a></span>
                <span class="badge bg-info text-dark"><a href="/courses/search-courses/competitive programming/" class="text-dark text-decoration-none">Competitive programming</a></span>
                <span class="badge bg-info text-dark"><a href="/courses/search-courses/android/" class="text-dark text-decoration-none">Android development</a></span>
                <span class="badge bg-info text-dark"><a href="/courses/search-courses/web development/" class="text-dark text-decoration-none">Web development</a></span>
                <span class="badge bg-info text-dark"><a href="/courses/search-courses/investing/" class="text-dark text-decoration-none">Investing</a></span>
                <span class="badge bg-info text-dark"><a href="/courses/search-courses/machine learning/" class="text-dark text-decoration-none">Machine learning</a></span><br>
                <span class="badge bg-info text-dark"><a href="/courses/search-courses/data structures/" class="text-dark text-decoration-none">Data structures</a></span>

              </div>


              
              <!--<div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>-->



            <div class="single-form-max-width pt-3 mx-auto">
                <form class="signup-form row g-2 g-lg-2 align-items-center" method="post" action="{% url 'sinx:search-courses' %}">
                  {% csrf_token %}
                          <div class="col-12 col-md-10">
                              <label class="sr-only" for="semail">Search courses</label>
                              <input type="search" id="semail" name="course-tag" class="form-control me-md-1 semail" placeholder="Enter topic name">
                          </div>
                          <div class="col-12 col-md-2">
                              <button type="submit" class="btn btn-primary">Search</button>
                          </div>
                </form>

            </div>
            

      </section>

    <section class="blog-list px-3 py-5 p-md-5">
      <div class="container single-col-max-width">


        {% for i in courses %}
        <div class="item mb-5">
          <div class="row g-3 g-xl-0">
            <div class="col-2 col-xl-3">
                <img class="img-fluid post-thumb " src="{{i.image.url}}" alt="image">
            </div>
            <div class="col">
              <h3 class="title mb-1"><a class="text-link" href="{% url 'sinx:course-overview' i.id %}">{{i.name}}</a></h3>
              <div class="meta mb-1"><span class="date">Author: <b>{{i.author}}</b></span><span class="comment"><b>Rating</b> <mark class="bg-success text-white m-2 px-2">{{i.overall_rating}} <i class="fa fa-star" aria-hidden="true" style="color:yellow;"></i></mark></span>
              <span class="comment">Platform: <b>{{i.platform}}</b></span>{% if i.price == 0 %}<span class="comment">Fees: <mark>Free</mark></span>{% else %}<span class="comment">Fees: {{i.price}}</span>{% endif %}</div>


              <div class="intro mt-5">{{i.description|safe}}</div>

              <a class="text-link text-info" href="{% url 'sinx:course-overview' i.id %}">Know more &rarr;</a>
            </div><!--//col-->
          </div><!--//row-->
        </div><!--//item-->

        {% empty %}

        {% if watchlist %}
        {% else %}

          {% if flag %}
          <h4 class="text-center">No course found.</h4>
          {% else %}
          <h4 class="text-center">No courses added yet.</h4>
          {% endif %}

        {% endif %}


        {% endfor %}

          {% if watchlist %}

          {% else %}

            {% if flag1 %}

            {% else %}
              <h4 class="text-center">No more courses.</h4>

            {% endif %}

          {% endif %}
              
      </div>
      
      </div>
    </section>

    {% if watchlist %}

      <section class="blog-list px-3 py-5 p-md-5">
        <div class="container single-col-max-width">


          {% for i in watchlist_courses %}
          <div class="item mb-5">
            <div class="row g-3 g-xl-0">
              <div class="col-2 col-xl-3">
                  <img class="img-fluid post-thumb " src="{{i.courses.image.url}}" alt="image">
              </div>
              <div class="col">
                <h3 class="title mb-1"><a class="text-link" href="{% url 'sinx:course-overview' i.courses.id %}">{{i.courses.name}}</a></h3>
                <div class="meta mb-1"><span class="date">Author: <b>{{i.courses.author}}</b></span><span class="comment"><b>Rating</b> <mark class="bg-success text-white m-2 px-2">{{i.courses.overall_rating}} <i class="fa fa-star" aria-hidden="true" style="color:yellow;"></i></mark></span>
                <span class="comment">Platform: <b>{{i.courses.platform}}</b></span>{% if i.courses.price == 0 %}<span class="comment">Fees: <mark>Free</mark></span>{% else %}<span class="comment">Fees: {{i.courses.price}}</span>{% endif %}</div>


                <div class="intro mt-5">{{i.courses.description|safe}}</div>

                <a class="text-link text-info" href="{% url 'sinx:course-overview' i.courses.id %}">Know more &rarr;</a>
                <br>
                <span class="mt-2 mb-2 text-center">
                 
                  <a class="text-decoration-none" type="button" data-toggle="collapse" data-target="#delete{{i.id}}" aria-expanded="false" aria-controls="delete{{i.id}}">
                  Remove
                  </a>

                  <div class="collapse" id="delete{{i.id}}">
                      <div class="card card-body my-2">

                          <h5 class="card-title text-danger text-center">Are you sure?</h5>
                          <div>

                          <a href = "{% url 'sinx:delete-from-watchlist' i.courses.id %}" class="m-1 filled-button text-center" style="text-decoration: none;">Yup!</a>

                            
                          </div>
                          
                      </div>
                  </div>
                  
                </span>
              </div><!--//col-->
            </div><!--//row-->
          </div><!--//item-->




          {% empty %}

            <h4 class="text-center">Watchlist is Empty.</h4>

          {% endfor %}
 
        </div>
        
        </div>
      </section>

    {% endif %}




{% endblock %}

{% block ajaxbox %}

    <script>

        const ele = document.getElementById("msg-container")
        setTimeout(function(){

            ele.style.display = "none";
            },
         3000);


    </script>
{% endblock %}