diary/urls.py
from django.urls import path
from . import views
app_name = 'sinx'

urlpatterns = [

	
	path("", views.all_courses, name = "sinx"),
	path("overview/<int:course_id>/", views.course_overview, name = "course-overview"),
	path("rate/<int:course_id>/", views.course_rating, name = "course-rating"),
	path("search-courses/", views.search_courses, name = "search-courses"),
	path("search-courses/<str:tag>/", views.search_courses_by_tag, name = "search-courses-by-tag"),
	path("add-to-watchlist/<int:course_id>/", views.add_to_watchlist, name = "add-to-watchlist"),
	path("view-watchlist/", views.view_watchlist, name = "view-watchlist"),
	path("share-course/<int:course_id>/", views.share, name = "share"),
	path("delete-shared-course/<int:course_id>/<int:club_id>/", views.delete_shared_course, name = "delete-shared-course"),
	path("delete-from-watchlist/<int:course_id>/", views.manage_watchlist, name = "delete-from-watchlist"),



]

doubts/urls.py
from django.urls import path
from .views import clubQuestions, deleteQuestion, updateQuestion, updateAnswere, addAnswere, deleteAnswere, userQuestion, userAnswer

app_name = 'qna'

urlpatterns = [
    #path('', questionListView , name='question-view'),
    #path('addquestion/<int:club_id>/', addQuestion , name='add-question-view'),
    path('delete-ques/<slug:pk>/', deleteQuestion, name='delete-question-view'),
    path('update-question/<slug:pk>/', updateQuestion, name='update-question-view'),
    path('add-answere/<int:id>/', addAnswere, name='add-answere-view'),
    path('update-answere/<slug:pk>/', updateAnswere, name='update-answere-view'),
    path('delete-answere/<slug:pk>/', deleteAnswere, name='delete-answere-view'),
    path('your-question/', userQuestion, name='your-question-view'),
    path('your-answer/', userAnswer, name='your-answer-view'),
    #path('filter-questions/<str:tag>/', questionTags, name='filter-questions'),
    #path('questions-scroll/<int:visible>/', QuestionJsonListView.as_view(), name='questions-scroll'),
    path('club-qna/<int:club_id>/', clubQuestions, name='club-qna'),


]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path
#from django.conf.urls import url
from accounts.views import index, donation
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("", index, name="index"),
    path('admin/', admin.site.urls),
    #path('chat/', include('django_chatter.urls', namespace = 'django_chatter'), name="chat"),
    path('accounts/', include('accounts.urls')),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
    path('users/', include('users.urls')),
    #path('courses/', include('courses.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('qna/', include('doubts.urls', namespace='qna')),
    path('quiz/', include('quizes.urls', namespace='quizes')),
    path('courses/', include('diary.urls', namespace = 'sinx')),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('accounts/password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('accounts/password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
    path("suPpoRt/", donation, name = "support"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [

    path("register/", views.register, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("delete-account/", views.deleteaccount, name="delete-account"),
    path("update-info/<int:pk>/", views.UpdateInfo.as_view(), name="update-info"),
    path("verify/<str:auth_token>/", views.verify, name="verify"),

]

doubts/models.py
from django.db import models
from django.contrib.auth.models import User
from diary.models import Course
from taggit.managers import TaggableManager
from accounts.models import clubInfo
# Create your models here.

class Question(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tag = TaggableManager()
    title = models.CharField(max_length=2000)
    detail = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null = True)
    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name_plural = "Questions"

class Answere(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ans = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null = True)

    def __str__(self):
        return f"{self.question.title}"

    class Meta:
        verbose_name_plural = "Answeres"



class ClubQuestion(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tag = TaggableManager()
    title = models.CharField(max_length=2000)
    detail = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    club = models.ForeignKey(clubInfo, on_delete=models.CASCADE, null = True)
    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name_plural = "Questions"


class ClubQuestionAnswere(models.Model):

    question = models.ForeignKey(ClubQuestion, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ans = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null = True)

    def __str__(self):
        return f"{self.question.title}"

    class Meta:
        verbose_name_plural = "Answeres"

qna/models.py
from django.db import models
from django.contrib.auth.models import User
from course_diary.models import Course
from taggit.managers import TaggableManager
from accounts.models import clubInfo
# Create your models here.

class Question(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tag = TaggableManager()
    title = models.CharField(max_length=2000)
    detail = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null = True)
    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name_plural = "Questions"

class Answere(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ans = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null = True)

    def __str__(self):
        return f"{self.question.title}"

    class Meta:
        verbose_name_plural = "Answeres"



class ClubQuestion(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tag = TaggableManager()
    title = models.CharField(max_length=2000)
    detail = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    club = models.ForeignKey(clubInfo, on_delete=models.CASCADE, null = True)
    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name_plural = "Questions"


class ClubQuestionAnswere(models.Model):

    question = models.ForeignKey(ClubQuestion, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ans = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null = True)

    def __str__(self):
        return f"{self.question.title}"

    class Meta:
        verbose_name_plural = "Answeres"

questions/models.py
# Create your models here.
from django.db import models
from quizes.models import Quiz

class Question(models.Model):
    text = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.text)

    def get_answers(self):
        return self.answers.all()


class Answer(models.Model):
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="answers")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"

doubts/forms.py
from django import forms
from django.forms import fields, widgets
from .models import Answere, Question
from django_summernote.widgets import SummernoteWidget
from django_summernote.fields import SummernoteTextFormField

INTERSET_CHOICES = [

    ("web-developement", "web-developement"),
    ("machine-learning", "machine-learning"),
    ("android-developement", "android-developement"),
    ("designing", "designing"),
    ("video-editing", "video-editing"),
    ("content-writting", "content-writting"),
    ("marketing", "marketing"),

    ("general", "general"),
    ("competitive programming", "competitive programming"),
]

class QuestionForm(forms.Form):

    title = forms.CharField(max_length=2000, label = "Title", widget = forms.Textarea(attrs = {'class': 'form-control', 'placeholder': 'title', 'rows': 0}))
    tag = forms.CharField(label = "Tags", widget = forms.Textarea(attrs = {'placeholder': 'css,html,javascript...', 'rows': 0}))
    detail = forms.CharField(label = "Details", widget = forms.Textarea(attrs = {'id': 'summernote'}))
    

class AnswereForm(forms.Form):
    answere = forms.CharField(label = "Your Answer", widget = SummernoteWidget())

class UpdateAnswereForm(forms.ModelForm):
    
    ans = forms.CharField(label ="Your answer", widget = forms.Textarea(
    attrs ={
        'class':'form-control',
        'id':'summernote',
    }))

    class Meta:

        model = Answere
        fields = ["ans"]

        widgets = {"ans": forms.Textarea(attrs={'cols': 80, 'rows': 20, 'id': 'summernote'}),
        }


    
class UpdateQuestionForm(forms.ModelForm):
    

    class Meta:

        model = Question
        fields = ["title", "tag", "detail"]

        widgets = {"detail": forms.Textarea(attrs={'cols': 80, 'rows': 20, 'id': 'summernote'}),
        }


class QuestionSearchForm(forms.Form):
    tags = forms.ChoiceField(choices=INTERSET_CHOICES, widget = forms.Select(attrs = {'class': 'form-control border-dark text-center', "style": "font-size:16px;", "id": "tag"}))

doubts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from datetime import datetime, time, date
from .models import Question, Answere, ClubQuestion, ClubQuestionAnswere
from django.views.generic import View
from django.contrib import messages
from django.contrib.auth.models import User
from accounts.models import eventRegistration, Members, clubInfo
from .forms import QuestionForm, AnswereForm, UpdateAnswereForm, UpdateQuestionForm, QuestionSearchForm
from django.http import HttpResponseRedirect, request, HttpResponse, JsonResponse
# Create your views here.


####### Questions ==============================================================>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


def clubQuestions(request, club_id):

    club = clubInfo.objects.get(id = club_id)
    
    club_questions = ClubQuestion.objects.filter(club = club)

    form = QuestionForm()

    member, created = Members.objects.get_or_create(memname = request.user)

    user_clubs = member.club.all()


    if request.method == 'POST':

        form = QuestionForm(request.POST)

        if form.is_valid():

            title = form.cleaned_data['title']
            tags = form.cleaned_data['tag']
            detail = form.cleaned_data['detail']
            club_id = request.POST['club-name']
            club = clubInfo.objects.get(id = club_id)

            question = ClubQuestion.objects.create(user = request.user, club = club, title = title, tag = tags, detail = detail)
            question.save()

            return redirect(f"/qna/club-qna/{club_id}/")

    return render(request, "qna/club-qna.html", {"questions": club_questions, "club_id": club_id, "form": form, "user_clubs": user_clubs})





def deleteQuestion(request, pk):
    
    obj = get_object_or_404(ClubQuestion, id = pk)

    if obj.user == request.user:
        obj.delete()
        return redirect("qna:your-question-view")

    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))




def updateQuestion(request, pk):

    context ={}

    obj = get_object_or_404(ClubQuestion, id = pk)

    form = UpdateQuestionForm(request.POST or None, instance = obj)

    user_clubs, created = Members.objects.get_or_create(memname = request.user)

    if request.method == 'POST':


        if form.is_valid():

            tags, title, detail, club_id = form.cleaned_data['tag'], form.cleaned_data['title'], form.cleaned_data['detail'], request.POST['club-name']

            club = clubInfo.objects.get(id = club_id)

            question = ClubQuestion.objects.create(user = request.user, tag = tags, title = title, detail = detail, club = club)

            messages.success(request, "Question updated.")
            return redirect(f"/qna/add-answere/{pk}/")
 

    return render(request, "qna/questionform.html", {"form": form, "user_clubs": user_clubs.club.all()})





##### Answeres =====================================================================================>>>>>>>>>>>>>>>>>>

def addAnswere(request, id):

    question = ClubQuestion.objects.get(id = id)
    a = ClubQuestionAnswere.objects.filter(question=question, parent = None)
    replies = ClubQuestionAnswere.objects.filter(question = question).exclude(parent = None)

    replyDict={}
    form = UpdateAnswereForm()
    for reply in replies:

        if reply.parent.id not in replyDict.keys():
            replyDict[reply.parent.id]=[reply]
        else:
            replyDict[reply.parent.id].append(reply)

    if request.method == 'POST':
        
        form = UpdateAnswereForm(request.POST or None)

        if form.is_valid():

            user = request.user
            parentSno = request.POST.get('parent')
            parent_ans = request.POST.get('parent_ans')


            if parentSno == "ans":  
                foo = form.cleaned_data['ans']
                        
                ans  = ClubQuestionAnswere(ans = foo, user = user, question = question)
                ans.save()
                messages.success(request, "Your ans has been posted successfully")

            elif parent_ans:

                foo = request.POST.get('answer1', 'blank')
                parent = ClubQuestionAnswere.objects.get(id = parent_ans)
                reply = ClubQuestionAnswere(ans = foo, user = user, question = question, parent = parent)
                reply.save()

                messages.success(request, "Your reply has been posted successfully")


            replies = ClubQuestionAnswere.objects.filter(question = question).exclude(parent = None)

            replyDict={}

            for reply in replies:

                if reply.parent.id not in replyDict.keys():
                    replyDict[reply.parent.id]=[reply]
                else:
                    replyDict[reply.parent.id].append(reply)
                    
            #ajax
            return render(request, "qna/answereform.html", {"i": question, "answeres": a, "total_q": len(a), "replyDict": replyDict, "form": form})

    return render(request, "qna/answereform.html", {"i": question, "answeres": a, "total_q": len(a), "replyDict": replyDict, "form": form})



def updateAnswere(request, pk):


    context ={}
    obj = get_object_or_404(ClubQuestionAnswere, id = pk)
    form = UpdateAnswereForm(request.POST or None, instance = obj) 


    if form.is_valid():
        form.save()
        return redirect(f"/qna/add-answere/{obj.question.id}/")       

    return render(request, "qna/answere-update-form.html", {"form": form})




def deleteAnswere(request, pk):
    
    obj = get_object_or_404(ClubQuestionAnswere, id = pk)

    if obj.user == request.user:
        obj.delete()
        return redirect("qna:your-answer-view")

    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))




def userQuestion(request):

    questions = ClubQuestion.objects.filter(user=request.user)
    return render(request, "qna/yourquestion.html", {"questions": questions})



def userAnswer(request):

    ans = ClubQuestionAnswere.objects.filter(user = request.user)
    return render(request, "qna/yourans.html", {"ans": ans})

questions/views.py
from django.shortcuts import render

# Create your views here.

doubts/templates/qna/answere-update-form.html
{% extends 'qna/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Update Answere{% endblock %}

{% load static %}
{% block script %}

    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

{% endblock %}


{% block main %}



<main class="container pt-100 mt-5 mb-5">

    <form  method="post" class="text-dark">

        {% csrf_token %}
        
        {{form|crispy}}

        <button class="btn btn-outline-dark  mt-3 mb-3 text-right" type="submit">Update</button>
    </form>

    

</main>


<script>
  $('#summernote').summernote({
    tabsize: 2,
    height: 100,

  });
</script>

{% endblock%}

doubts/templates/qna/club-qna.html
{% extends 'qna/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Q&A{% endblock %}
{% load humanize %}

{% block script %}

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
  
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <style type="text/css">

        .filled-button {
            background-color: transparent;
            color: #fff;
            background-color: #515148;
            border: none;
            font-size: 13px;
            text-transform: uppercase;
            font-weight: 700;
            padding: 12px 30px;
            border-radius: 30px;
            display: inline-block;
            transition: all 0.3s;
            outline: none;
            box-shadow: none;
            text-shadow: none;
            cursor: pointer;
        }
           
        .filled-button:hover {
            background-color: #17b978;
            color: white;
        }



      .blog-post {
        margin-bottom: 4rem;
      }
      .blog-post-title {
        margin-bottom: .25rem;
        font-size: 2.5rem;
      }
      .blog-post-meta {
        margin-bottom: 1.25rem;
        color: #727272;
      }



  </style>
{% endblock %}

{% block main %}

 
<div class="container text-center mb-5 mt-5 pt-2 pb-5">  


  
    <div class="row">
      <div class="col">

        <div class="card mt-2 mb-2">


          <div class="card-body">

            <!-- Modal -->
            <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header text-center">
                    <h5 class="modal-title text-dark" id="staticBackdropLabel">Ask Doubts</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">

                    <form class="p-4 p-md-5 border rounded-3 bg-light text-dark text-start" action="{% url 'qna:club-qna' club_id %}" enctype="multipart/form-data" method="post">

                      {% csrf_token %}

                      
                      {{form|crispy}}



                      <div class="form-floating mb-3 mt-3">

                        <select class="form-select" aria-label="Default select example" name="club-name" id="floatingSelect">
                          {% for i in user_clubs %}
                            <option value="{{i.id}}"  class="text-dark">{{i.name}}</option>
                          {% endfor %}
                        </select>
                        <label for="floatingSelect">Club</label>

                      </div>


                      <div class="text-center">
                        <button type="submit" class="filled-button mb-5 mt-5">Ask</button>
                      </div>

                    </form>
                    
                  </div>
                </div>
              </div>
            </div>


            <!-- Button trigger modal -->
            <div class="text-center">

              {% if request.user.is_authenticated %}
              <a class="filled-button text-decoration-none mb-4 mt-3 " class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                Ask Doubts
              </a>
              <a  href="{% url 'qna:your-question-view' %}" style="font-size: 12px; text-decoration: none;">Your questions</a>
              <a  href="{% url 'qna:your-answer-view' %}" style="font-size: 12px; text-decoration: none;">Your answers</a>
              {% else %}

                <a href="{% url 'users:register' %}" class="filled-button mt-2" style="text-decoration: none;">Sign up</a>

              {% endif %}
              
            </div>


            
          </div>
        </div>


      </div>

    </div>

        <div class="row mt-5">
          {% for i in questions %}


            <article class="blog-post">
              <h2 class="blog-post-title text-dark"><a href="{% url 'qna:add-answere-view' i.id %}" class="text-success text-decoration-none text-dark">{{i.title}}</a></h2>
              <p class="blog-post-meta text-dark">{{i.time|naturaltime}} by <a href="{% url 'info' i.user.username %}">{{i.user.username}}</a></p>

              <h6 class="text-dark"><a href="{% url 'qna:add-answere-view' i.id %}" class="text-success text-decoration-none text-dark">{{i.detail|safe|truncatewords:30}}</a></h6>


            </article>


              {% if request.user == i.user %}
                  
                  <span>


                    <a href = "{% url 'qna:update-question-view' i.id  %} " class="text-decoration-none m-1">update</a>

                    <a class="text-decoration-none" type="button" data-toggle="collapse" data-target="#deleteBox{{i.id}}" aria-expanded="false" aria-controls="deleteBox{{i.id}}">
                    delete
                    </a>

                    <div class="collapse" id="deleteBox{{i.id}}">
                        <div class="card card-body my-2">

                            <h5 class="card-title text-danger">Are you sure?</h5>
                            <a href = "{% url 'qna:delete-question-view' i.id  %} " class="text-decoration-none m-1">Yup!</a>
                            
                        </div>
                    </div>


                  </span>
                  
                  
              {% endif %}

            <hr class="text-dark">
          {% endfor %}

        </div>



</div>



<script>
  $('#summernote').summernote({
    placeholder: 'Your Question here!',
    tabsize: 2,
    height: 100,

  });
</script>

{% endblock%}

{% block ajaxbox %}

  <script type="text/javascript">
    
  </script>

{% endblock %}

doubts/templates/qna/yourans.html
{% extends 'qna/base.html' %}

{% block title %}Your Answers{% endblock %}
{% load humanize %}

{% block script %}



    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">

    <style type="text/css">
        
        .blog-post {
          margin-bottom: 4rem;
        }
        .blog-post-title {
          margin-bottom: .25rem;
          font-size: 2.5rem;
        }
        .blog-post-meta {
          margin-bottom: 1.25rem;
          color: #727272;
        }


    </style>

{% endblock %}
{% block main %}


<main class="container mt-5">


    {% for i in ans %}
        <article class="blog-post">
          <h2 class="blog-post-title text-dark"><a href="{% url 'qna:add-answere-view' i.id %}" class="text-success text-decoration-none text-dark">{{i.question.title}}</a></h2>
          <p class="blog-post-meta text-dark">{{i.time|naturaltime}} by <a href="{% url 'info' request.user.username %}">You</a></p>

          <h6 class="text-dark"><a href="{% url 'qna:add-answere-view' i.id %}" class="text-success text-decoration-none text-dark">{{i.ans|safe|truncatewords:15}}</a></h6>


          <a href = "{% url 'qna:update-answere-view' i.id  %} " class="m-1" style="text-decoration: none;">update</a>
          <!--<a href = "{% url 'qna:delete-answere-view' i.id  %} " class="m-1" style="text-decoration: none;">delete</a>-->

          <a class="text-decoration-none" type="button" data-toggle="collapse" data-target="#deleteBox{{i.id}}" aria-expanded="false" aria-controls="deleteBox{{i.id}}">
          delete
          </a>

          <div class="collapse" id="deleteBox{{i.id}}">
              <div class="card card-body my-2">

                  <h5 class="card-title text-danger">Are you sure?</h5>
                  <div class="text-start">

                    <a href = "{% url 'qna:delete-answere-view' i.id  %} " class="m-1 filled-button text-decoration-none" >Yup!</a>
                    
                  </div>
                  
                  
              </div>
          </div>


        </article>

        <hr class="text-dark">

    {% empty %}

        <div class="text-center mt-5 mb-5 py-5">

            <h6 class="text-dark">No answers yet.</h6>
            
        </div>
        

    {% endfor %}
    
</main>



{% endblock%}