diary/urls.py
from django.urls import path
from . import views
app_name = 'sinx'

urlpatterns = [

	
	path("", views.all_courses, name = "sinx"),
	path("overview/<int:course_id>/", views.course_overview, name = "course-overview"),
	path("rate/<int:course_id>/", views.course_rating, name = "course-rating"),
	path("search-courses/", views.search_courses, name = "search-courses"),
	path("search-courses/<str:tag>/", views.search_courses_by_tag, name = "search-courses-by-tag"),
	path("add-to-watchlist/<int:course_id>/", views.add_to_watchlist, name = "add-to-watchlist"),
	path("view-watchlist/", views.view_watchlist, name = "view-watchlist"),
	path("share-course/<int:course_id>/", views.share, name = "share"),
	path("delete-shared-course/<int:course_id>/<int:club_id>/", views.delete_shared_course, name = "delete-shared-course"),
	path("delete-from-watchlist/<int:course_id>/", views.manage_watchlist, name = "delete-from-watchlist"),



]

doubts/urls.py
from django.urls import path
from .views import clubQuestions, deleteQuestion, updateQuestion, updateAnswere, addAnswere, deleteAnswere, userQuestion, userAnswer

app_name = 'qna'

urlpatterns = [
    #path('', questionListView , name='question-view'),
    #path('addquestion/<int:club_id>/', addQuestion , name='add-question-view'),
    path('delete-ques/<slug:pk>/', deleteQuestion, name='delete-question-view'),
    path('update-question/<slug:pk>/', updateQuestion, name='update-question-view'),
    path('add-answere/<int:id>/', addAnswere, name='add-answere-view'),
    path('update-answere/<slug:pk>/', updateAnswere, name='update-answere-view'),
    path('delete-answere/<slug:pk>/', deleteAnswere, name='delete-answere-view'),
    path('your-question/', userQuestion, name='your-question-view'),
    path('your-answer/', userAnswer, name='your-answer-view'),
    #path('filter-questions/<str:tag>/', questionTags, name='filter-questions'),
    #path('questions-scroll/<int:visible>/', QuestionJsonListView.as_view(), name='questions-scroll'),
    path('club-qna/<int:club_id>/', clubQuestions, name='club-qna'),


]

mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path
#from django.conf.urls import url
from accounts.views import index, donation
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path("", index, name="index"),
    path('admin/', admin.site.urls),
    #path('chat/', include('django_chatter.urls', namespace = 'django_chatter'), name="chat"),
    path('accounts/', include('accounts.urls')),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
    path('users/', include('users.urls')),
    #path('courses/', include('courses.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('qna/', include('doubts.urls', namespace='qna')),
    path('quiz/', include('quizes.urls', namespace='quizes')),
    path('courses/', include('diary.urls', namespace = 'sinx')),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('accounts/password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('accounts/password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
    path("suPpoRt/", donation, name = "support"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

quizes/urls.py
from django.urls import path
from .views import QuizListView, quiz_view, quiz_data_view, save_quiz_view, RecentQuizzes, quizform, TestCreate

app_name = 'quizes'

urlpatterns = [
    path('', QuizListView, name='main-view'),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/save/', save_quiz_view, name='save-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
    path('recent-quizzes', RecentQuizzes, name='recent-quizzes'),
    path('quiz-form', TestCreate.as_view(), name='quizform'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [

    path("register/", views.register, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("delete-account/", views.deleteaccount, name="delete-account"),
    path("update-info/<int:pk>/", views.UpdateInfo.as_view(), name="update-info"),
    path("verify/<str:auth_token>/", views.verify, name="verify"),

]

quizes/models.py
# Create your models here.
from django.db import models
from accounts.models import clubInfo
import random
from django_resized import ResizedImageField

DIFF_CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)

class Quiz(models.Model):
    #connect it to club's
    club = models.ForeignKey(clubInfo, on_delete=models.CASCADE)
    img = ResizedImageField(size=[300, 300],upload_to="quiz_poster/")
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    required_score_to_pass = models.IntegerField(help_text="required score in %")
    difficluty = models.CharField(max_length=6, choices=DIFF_CHOICES)

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_questions(self):
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]


    class  Meta:
    	verbose_name_plural = "Quizes"
    		

quizes/forms.py
from django import forms
from django.forms import fields, widgets
from questions.models import Question, Answer
from django.forms import ModelForm, inlineformset_factory


class QuestionForm(ModelForm):
    class Meta:
        model = Question
        exclude = ()


class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        exclude = ()


QuizFormSet = inlineformset_factory(
    Question, Answer, form=AnswerForm, extra=1)

quizes/views.py
# Create your views here.
from django.shortcuts import render
from .models import Quiz
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import Question, Answer
from results.models import Result
import statistics
from .forms import QuizFormSet, QuestionForm, AnswerForm
from django.views.generic import CreateView, DeleteView, ListView, UpdateView


def  QuizListView(request):

    quiz  = Quiz.objects.all()

    recent = ""

    if request.user.is_authenticated:
        recent = Result.objects.filter(user = request.user).order_by("-id")[:3] 

    return render(request, 'quizes/main.html', {"object_list": quiz, "recent_quizzes": recent})

def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html', {'obj': quiz})


def quiz_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_questions():
        answers = []
        for a in q.get_answers():
            answers.append(a.text)
        questions.append({str(q): answers})
    return JsonResponse({
        'data': questions,
        'time': quiz.time,
    })


def save_quiz_view(request, pk):
    if request.is_ajax():
        questions = []
        data = request.POST
        data_ = dict(data.lists())

        data_.pop('csrfmiddlewaretoken')

        for k in data_.keys():
            print('key: ', k)
            question = Question.objects.get(text=k)
            questions.append(question)
        print(questions)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)

            if a_selected != "":
                question_answers = Answer.objects.filter(question=q)
                for a in question_answers:
                    if a_selected == a.text:
                        if a.correct:
                            score += 1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text

                results.append({str(q): {'correct_answer': correct_answer, 'answered': a_selected}})
            else:
                results.append({str(q): 'not answered'})
            
        score_ = score * multiplier
        Result.objects.create(quiz=quiz, user=user, score=score_)

        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed': True, 'score': score_, 'results': results})
        else:
            return JsonResponse({'passed': False, 'score': score_, 'results': results})


def RecentQuizzes(request):

    recent = Result.objects.filter(user = request.user)

    data = []
    for i in recent:

        foo = Result.objects.filter(quiz = i.quiz)

        scores = [i.score for i in foo]

        data.append((len(foo), round(statistics.mean(scores))))

    return render(request, "quizes/recent-quiz.html", {"recent": zip(recent, data)})


def quizform(request):


    form = QuizFormSet()
    form1 = QuestionForm()
    form2 = AnswerForm()


    return render(request, "quizes/quizform.html", {"form": form, "form1": form1, "form2": form2})


class TestCreate(CreateView):


    def get(self, request, *args, **kwargs):
        context = {
          'form': QuestionForm(), # form used to create model_A instance(s)
          'formset': QuizFormSet(), # formset for create model_B instace(s) linked to that model_A instace
        }

        return render(request, 'quizes/quizform.html', context)


    def post(self, request, *args, **kwargs):
        # if our ajax is calling so we have to take action
        # because this is not the form submition
        if request.is_ajax():
            cp = request.POST.copy() # because we couldn't change fields values directly in request.POST
            value = int(cp['wtd']) # figure out if the process is addition or deletion
            prefix = "answers" # whatever your related_name is
            cp[f'{prefix}-TOTAL_FORMS'] = int(
                cp[f'{prefix}-TOTAL_FORMS']) + value
            formset = QuizFormSet(cp) # catch any data which were in the previous formsets and deliver to-
              # the new formsetes again -> if the process is addition!
            return render(request, 'quizes/formset.html', {'formset': formset})

        form = QuestionForm(request.POST)
        formset = QuizFormSet(request.POST or None)
        theres_no_error = True # a good tip, you'll see ;)
        # important note: check any desired validation of formset here and it's helpful
        # to prevent save model_A instance if formset contains invalid data which-
        # means connected model_B instance(s) wont be created

        """
        if formset.is_valid():

           
            for subform in formset:
              if subform.cleaned_data['custom_field'] is not valid_in_your_opinion: # the formset is valid but-
                # you want to check something if you'relike me crazy
                theres_no_error = False
                subform.full_clean()
                subform.errors['custom_field'] = subform.error_class(["yor message to show error"])"""

        print(form.is_valid(), formset.is_valid())
        
        if form.is_valid() and theres_no_error and formset.is_valid(): # if formsets are valid too! :)
            form.save()

            for subform in formset:

                subform.save()

quizes/templates/quizes/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    
    <style type="text/css">
      
        body{


            background-color: #f3f7f8;
            color: white;


        }

        .filled-button {
            background-color: transparent;
            color: white;
            background-color: green;
            border: none;
            font-size: 13px;
            text-transform: uppercase;
            font-weight: 700;
            padding: 12px 30px;
            border-radius: 30px;
            display: inline-block;
            transition: all 0.3s;
            outline: none;
            box-shadow: none;
            text-shadow: none;
            cursor: pointer;
        }
        
    </style>

    {% block script %}
    {% endblock script %}


    <title>cosb | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}">cosb</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">


              {% if not request.user.is_authenticated %}

                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:register' %}">Sign up</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:login' %}">Sign in</a>
                </li>

              {% endif %}

              {% if request.user.is_authenticated %}

                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Clubs</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'sinx:sinx' %}">Courses</a>
                </li>


                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'users:logout' %}">Log Out</a>
                </li>

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{request.user.username}}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'password_reset' %}">Change Password</a></li>
                    <!--<li><a class="dropdown-item" href="{% url 'users:update-info' request.user.id  %}">Update Profile</a></li>-->
                    <li><a class="dropdown-item" href="{% url 'sinx:view-watchlist' %}">Your Watchlist</a></li>
                    <li><a class="dropdown-item" href="{% url 'qna:your-question-view' %}">Your Questions</a></li>
                    <li><a class="dropdown-item" href="{% url 'qna:your-answer-view' %}">Your Answers</a></li>
                    <!--<li><a class="dropdown-item" href="{% url 'users:delete-account' %}">Delete Account</a></li>-->
                  </ul>

              {% endif %}

            </ul>
          </div>
        </div>
    </nav>


    {% block content %}
    {% endblock content %}

    
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header text-center">
            <h5 class="modal-title text-dark" id="staticBackdropLabel">Teach on cosb</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">

            <form class="p-4 p-md-5 border rounded-3 bg-light" action="{% url 'teach-on-cosb' %}" enctype="multipart/form-data" method="post">

              {% csrf_token %}

              <div class="form-floating mb-5">
                <input type="email" id="defaultForm" class="form-control text-dark" name="email" required placeholder="email">
                <label data-error="wrong" data-success="right" for="defaultForm" class="text-dark">Email</label>
              </div>


              <div class= "form-floating">

                <input type="text" id="msgForm" class="form-control text-dark" name="msg" required placeholder="What You Want to create?">
                <label data-error="wrong" data-success="right" for="msgForm" class="text-dark">What You Want to create?</label>
                
                
              </div>


              <div class="text-center">
                <button type="submit" class="filled-button mb-5 mt-5">Send</button>
              </div>

            </form>
            
          </div>
        </div>
      </div>
    </div>

    <footer class="text-center text-lg-start bg-dark text-light" id="myfooter">

      <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">

    
        <div class="me-5 d-none d-lg-block">
          <span>FOLLOW US</span>
        </div>


        <div>
          <!--
          <a href="" class="me-4 text-reset">
            <i class="fa fa-facebook"></i>
          </a>-->
          <a href="https://www.youtube.com/channel/UCA0wBopPNrrZSii4LYDDFPg" class="me-4 text-reset">
            <i class="fa fa-youtube"></i>
          </a>
          <!--
          <a href="" class="me-4 text-reset">
            <i class="fa fa-google"></i>
          </a>
          -->
          <a href="https://www.instagram.com/learn_on_cosb/" class="me-4 text-reset">
            <i class="fa fa-instagram"></i>
          </a>

          <!--
          <a href="" class="me-4 text-reset">
            <i class="fa fa-linkedin"></i>
          </a>
          <a href="" class="me-4 text-reset">
            <i class="fa fa-github"></i>
          </a>-->
        </div>

      </section>

      <section class="">
        <div class="container text-center text-md-start mt-5">

          <div class="row mt-3">

            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
    
              <h6 class="text-uppercase fw-bold mb-4">
                Teach on cosb
              </h6>

              
              <p>
                <a class="text-decoration-none text-reset" data-bs-toggle="modal" data-bs-target="#staticBackdrop" href="">
                  Teach on cosb                
                </a>
              </p>


              <!--<p>
                <a class="text-decoration-none text-reset" href="/suPpoRt/">
                  suPpoRt               
                </a>
              </p>-->
        
            </div>

    
    
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">


              <h6 class="text-uppercase fw-bold mb-4">
                Useful links
              </h6>

              {% if request.user.is_authenticated %}

                <p>
                  <a href="/accounts/club-by-tag/ALL/" class="text-reset text-decoration-none">Join a club</a>
                </p>
                
                <!--<p>
                  <a href="/quiz/" class="text-reset text-decoration-none">Take a quiz</a>
                </p>-->
                <p>
                  <a href="{% url 'club-registration' %}" class="text-reset text-decoration-none">Open Club</a>
                </p>
                <p>
                  <a href="{% url 'feedback' %}" class="text-reset text-decoration-none">Feedbacks</a>
                </p>

              {% else %}


                <!--<p>
                  <a href="/quiz/" class="text-reset text-decoration-none">Take a quiz</a>
                </p>-->


                <p>
                  <a href="/accounts/club-by-tag/ALL/" class="text-reset text-decoration-none">Join a club</a>
                </p>

              {% endif %}

            </div>
     
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

              <h6 class="text-uppercase fw-bold mb-4">
                Contact
              </h6>
          
              <p><i class="fa fa-envelope me-3"></i><a href="mailto:neeshamraghav0@gmail.com" class="text-decoration-none text-white">Send Email</a></p>
              <p><i class="fa fa-phone me-3"></i>7206126235</p>

            </div>
    
          </div>
    
        </div>
      </section>

      <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2021 cosb
        <a class="text-reset fw-bold text-decoration-none" href="#">Some rights reserved</a>
      </div>
    
    </footer>
    
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>

    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>

    <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>
 
    <script src = "https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script> 

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
  
  
    
  </body>
</html>

quizes/templates/quizes/formset.html
{% load static %}
{{ formset.management_form }}
{% for form in formset.forms %}
  <table id="duration" class="table table-striped table-inline table-responsive">
      {% if forloop.first %}
          <thead>
          <tr>
              {% for field in form.visible_fields %}
                  <th> {{ field.label }} </th>
              {% endfor %}
          </tr>
          </thead>
      {% endif %}
      <tbody>
          <tr class="formset_row">
              {% for field in form.visible_fields %}
                  <td>
                      {# Include the hidden fields in the form #}
                      {% if forloop.first %}
                          {% for hidden in form.hidden_fields %}
                              {{ hidden }}
                          {% endfor %}
                      {% endif %}
                      {{ field.errors.as_ul }}
                      {{ field }}
                  </td>
              {% endfor %}
          </tr>
      </tbody>
  </table>
{{ form.media }}
{% endfor %}

quizes/templates/quizes/quiz.html
{% extends "quizes/base.html" %}
{% load static %}

{% block script %}
    <script src="{% static 'quizes/quiz.js' %}" defer></script> 
    
{% endblock script %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}

<div class="container mt-5">

	<div class="row text-dark">
	    <div class="col">
	        <b>{{obj.name}}</b>
	        <p>score to pass: {{obj.required_score_to_pass}}%</p>
	    </div>
	    <div class="col text-right" id="timer-box"></div>
	</div>
	<a href="{% url 'quizes:main-view' %}" class="btn btn-danger">Go Back</a>
	

	<div class="row">


		<form id="quiz-form" class="mt-3 mb-3 text-dark">
		    {% csrf_token %}
		    <div id="quiz-box"></div>

		    {% if request.user.is_authenticated %}
		    	<button type="submit" class="btn btn-outline-dark mt-3" id="save">End Quiz</button>

		    {% else %}

		    <div class="mt-5">

		    	<a class="text-decoration-none" href="{% url 'users:login' %}">Sign in to check your score.</button>
		    	
		    </div>
		    	

		    {% endif %}


		</form>
		<div id="score-box" class="text-dark"></div>
		<div id="result-box" class="text-dark mb-5"></div>
		<div id="back-box" class="text-dark mt-2 mb-2"></div>
		



	</div>


		
</div>


{% endblock content %}

quizes/templates/quizes/quizform.html
{% extends "accounts/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Add-Tasks{% endblock %}
{% block main %}

<div class="container m-2">

  {% for msg in messages %}

      <div class="row">
          <p class="text-success text-center">{{msg}}</p>
      </div>
      
  {% endfor %}

</div>

<div class="container text-end">
  <a href="{% url 'recent-tasks' %}">Recent tasks.</a>
</div>

<main class="container pt-3">


<form id="form_with_formset" action="{% url 'quizes:quizform' %}" method="post">
  {% csrf_token %}
  <table class="table">
    {{ form.as_table }}
  </table>

  <!-- this inputs value indicates the we want to add or remove a row -->
  <input id="wtd" name="wtd" type="hidden" value="1">

  <div id="formset_container">
      {% include 'quizes/formset.html' %}
  </div>

  <button type="button" class="btn btn-info m-1 mb-5" data-target-url="{{ request.path }}" id="addNewRow">add new row</button>
  <button type="button" class="btn btn-warning m-1 mb-5" data-target-url="{{ request.path }}" id="remLastRow" disabled="disabled">delete last row</button>

  <button type="submit" class="btn btn-success m-1 mb-5">submit</button>
</form>


</main>

    

{% endblock %}

{% block ajaxbox %}

  <script type="text/javascript">
    
    $(document).ready(function() {

      // formset control
      $('#addNewRow').on('click', function(e) {
          e.preventDefault();

          var ajax_link = this.getAttribute('data-target-url');

          // +1 to indicate this a request to add new formset instance
          $('#form_with_formset').find('#wtd').val(1);

          $.ajax({
              url: ajax_link,
              data: $('#form_with_formset').serialize(),
              type: 'POST',

              success: function(res) {
                  // clear the formset container and then fill it with the-
                  // response of ajax call. the response contains the-
                  // previous formset instance plus one new instance 
                  $('#formset_container').empty();
                  $('#formset_container').append(res);
              }
          });

          $('#remLastRow').removeAttr('disabled');
      });

      $('#remLastRow').on('click', function(e) {
          e.preventDefault();

          var ajax_link = this.getAttribute('data-target-url');

          // at least one formset instance is mandatory
          if ($('#formset_container').children('table').length > 1) {

              // -1 to indicate this a request to remove the last formset instance
              $('#form_with_formset').find('#wtd').val(-1);

              // because I handled fromsets in separate tables so
              // for remove last instance we just remove the last child (table)
              $('#formset_container table').last().remove();

              $.ajax({
                  url: ajax_link,
                  data: $('#form_with_formset').serialize(),
                  type: 'POST',

                  success: function(res) {
                      $('#formset_container').empty();
                      $('#formset_container').append(res);
                  }
              });
          }
          // disabling remove button if just one instance remained
          if ($('#formset_container').children('table').length <= 1)
              $('#remLastRow').attr('disabled', 'true');
      });
  });
  </script>

{% endblock %}